### ISSUE TITLE
Not download all

### ISSUE THREAD

**Issue by SakerLy** [DIGITALCRIMINALS/UltimaScraper#1062]
I can't download it all
Ex: there are 187 vids in total but it only downloads 176 vids
and it doesn't show the number of duplicate files
Does anyone know how to fix it?

**Comment by marcintosch** [comment]
Are the other 11 videos PPV you haven't bought yet? Scraper will only download content you are allowed to view, so both subscribed and paid (for PPV) is necessary.

**Comment by wireman21** [comment]
many of the newer videos are DRM restricted making downloading harder
