### ISSUE TITLE
[Fansly] Stuck after selecting fansly site

### ISSUE THREAD

**Issue by huaiyin0416** [DIGITALCRIMINALS/UltimaScraper#1067]
<img width="468" alt="2023-08-14 164807" src="https://github.com/DIGITALCRIMINALS/UltimaScraper/assets/32978395/2aa22cf8-3fab-4ba7-8e4c-d8d943ad36aa">

What should I do?

**Comment by huaiyin0416** [comment]
I found a problem with the running directory 
![01363A94](https://github.com/DIGITALCRIMINALS/UltimaScraper/assets/32978395/49697c0c-3012-470d-a569-64cd93554d10)

**Comment by god43** [comment]
yeah this doesn't work
