### ISSUE TITLE
OF Scraping is significantly slower in recent script release

### ISSUE THREAD

**Issue by Nick05491** [DIGITALCRIMINALS/UltimaScraper#244]
I recently updated to Python 3.10.1 (as recommended in the 'README') and then downloaded an updated script directory (on Dec. 22nd at around 12:30pm EST) from the [main repository page](https://github.com/DIGITALCRIMINALS/OnlyFans) (by clicking "Code" --> "Download ZIP").  I re-ran the PIP installation, ran the script to generate the config files, and transfered over my settings from existing configs.

**After this update, the time it would take to scrape OF accounts was significantly slower.**  For example, I was seeing 20-30 minutes just to bulk scrape 6-7 users with typical post and message counts.  This would usually take <5 minutes before the update.

Previously I had been running a "v7.6" code with Python 3.10 (I had both 3.9 & 3.10 installed but I believe the 'python3 start_ofd.py' command would use the latest 3.10 release).  I had downloaded this code version on Dec. 3rd.  After I reverted back to this release from early December, the scraping speed went back to what I was used to.  So I don't think this is caused by the upgrade to Python 3.10.1.  It looks like there have been some updates since the code I had issues with.  I haven't tried any of these yet.  Figured I'd raise the issue here first to see if it was known and if it should be fixed in newer updates.

Below is the code I observed the slow scraping on for reference.
[OnlyFans-master.zip](https://github.com/DIGITALCRIMINALS/OnlyFans/files/7809790/OnlyFans-master.zip)

Thanks always to @DIGITALCRIMINALS and all other contributors.

**Comment by DIGITALCRIMINALS** [comment]
How many CPU threads do you have

**Comment by Nick05491** [comment]
> How many CPU threads do you have

Thanks for the response.  I use an old 2009 MBP for scrapping...  2.66 GHz Intel Core 2 Duo 😳 .  I understand this bad boy's a dinosaur, and wouldn't expect the code to be optimized for such an old system.  But was there a change made that would affect how dependent performance was on CPU threads?  Just wondering if that explains the slower speed.

**Comment by DIGITALCRIMINALS** [comment]
There was a change, yes. 
It's to do with network requests, some users were getting errors because there were too many requests, so I ended up making the script limit how many requests the script can do based on how many CPU threads you have.
I'll be sure to add in an option so it won't be limited to threads, which in your case would be 4 requests at a time which is slow... I've got 32 threads so I didn't realise 💀

**Comment by Nick05491** [comment]
> 

Great... thanks for all the work you do here.

**Comment by sintaxx** [comment]
I'm using a machine with 16 threads, 32GB DDR4 and a 1Gbps/1Gbps fiber connection and its also running fairly slow for me

**Comment by DIGITALCRIMINALS** [comment]
If you wanna boost it, you can change max_threads to 100

https://github.com/DIGITALCRIMINALS/OnlyFans/blob/38b3cf3a7a72fdfef7a50b648ae4848ed92ef579/apis/api_helper.py#L132

**Comment by zeldatp151** [comment]
I'm running 7.6.1 from dec, and self.semaphore = asyncio.BoundedSemaphore(max_threads)  doesn't exist in my api_helper.py, Can I just define max_threads = 100 and comment out the calculation? I only have 6 cores assigned to the vm, but its on a second gen EPYC and those 6 cores should be more than enough along side my gigabit fiber.

**Comment by DIGITALCRIMINALS** [comment]
Use the latest commit

**Comment by Miriyo** [comment]
> If you wanna boost it, you can change max_threads to 100+
> 
> https://github.com/DIGITALCRIMINALS/OnlyFans/blob/38b3cf3a7a72fdfef7a50b648ae4848ed92ef579/apis/api_helper.py#L132

How would it look like? Mine is like this but I haven't noticed a difference: self.semaphore = asyncio.BoundedSemaphore(100)
I have 12 threads

**Comment by DIGITALCRIMINALS** [comment]
> I'm running 7.6.1 from dec, and self.semaphore = asyncio.BoundedSemaphore(max_threads) doesn't exist in my api_helper.py, Can I just define max_threads = 100 and comment out the calculation? I only have 6 cores assigned to the vm, but its on a second gen EPYC and those 6 cores should be more than enough along side my gigabit fiber.

It won't work like that. In 7.6.1, network requests isn't limited to max threads you've got.
max_threads is used for how many metadatas we can process at a time.

**Comment by DIGITALCRIMINALS** [comment]
> > If you wanna boost it, you can change max_threads to 100+
> > https://github.com/DIGITALCRIMINALS/OnlyFans/blob/38b3cf3a7a72fdfef7a50b648ae4848ed92ef579/apis/api_helper.py#L132
> 
> How would it look like? Mine is like this but I haven't noticed a difference: self.semaphore = asyncio.BoundedSemaphore(100) I have 12 threads

I updated my comment to show an example:
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/244#issuecomment-1010394113

You won't really see a difference unless the model has thousands or even hundreds of posts.

**Comment by Nick05491** [comment]
> > I'm running 7.6.1 from dec, and self.semaphore = asyncio.BoundedSemaphore(max_threads) doesn't exist in my api_helper.py, Can I just define max_threads = 100 and comment out the calculation? I only have 6 cores assigned to the vm, but its on a second gen EPYC and those 6 cores should be more than enough along side my gigabit fiber.
> 
> It won't work like that. In 7.6.1, network requests isn't limited to max threads you've got. max_threads is used for how many metadatas we can process at a time.

@DIGITALCRIMINALS, when you say 'how many metadatas we can process at a time', does this include attempting to download medias that are not yet downloaded?  I've been fighting an issue over the past week or so where nothing's actually downloading when I run a bulk scrape of all my subs.  But if I select one model at a time to scrape, it's usually ok.  It seems like the issue is somehow related to the total number of medias being downloaded, or the rate of requests to the OF server.  Is there any easy way I could slow down the rate of download requests to troubleshoot this?

**Comment by A-Random-Mf** [comment]
@DIGITALCRIMINALS Does this still work on v 8.0.0? It seems to break the  script for me. Doesnt scrape

**Comment by god43** [comment]
it is set like this in the current version already. 

self.semaphore = asyncio.BoundedSemaphore(max_threads)
