### ISSUE TITLE
Simple Install

### ISSUE THREAD

**Issue by stranger-danger-zamu** [DIGITALCRIMINALS/UltimaScraper#343]
I have a pretty large [pull request](https://github.com/stranger-danger-zamu/OnlyFans/tree/feature/simple-install) pending to make this much easier to install by essentially (lightly) refactoring this all to make it a module which can be installed from wheel (and thus from pypi or from [github](https://matiascodesal.com/blog/how-use-git-repository-pip-dependency/) via a simple `pip install ultimascraper`).

There are a few blockers that I wouldn't want to push through until they were resolved.

* [x] Eliminating all `os.chdir` shenanigans.
* [ ] Having `settings` and `profiles` directories assignable from the CLI
* [x] Confirmation that the project would be called `ultimascraper` as per the project name in the `pyproject.toml` file
* [ ] Fixing the database location stuff
* [ ] Incorporate #226 for the configuration file

Currently, only the database issue is truly making this not work. Everything else is more or less patched to sorta work and/or commented out (looking at your `os.chdir`).

---

Edit (22/02/10): Added Issue 226 as a blocking issue since that'd also make the readability of some of the code base much nicer.

**Comment by stranger-danger-zamu** [comment]
My plan for the configuration directories (ie. `settings` and `profiles`) is to have them follow best practices according to the OS (ie. use appdirs). So:

* for Linux it'd be `$HOME/.config/ultimascraper/{settings,profiles}`, 
* Windows it'd be `C:\Documents and Settings\<User>\Application Data\Local Settings\<AppName>\{settings,profiles}`, and
* OSX has `$HOME/Library/Application Support/<AppName>/{settings,profiles}`

Then I'd probably have the `.sites` directory as a new setting in the `settings/config.json` file.

Of course I'd rather not do too much more without some input from you and the rest of the community.

**Comment by stranger-danger-zamu** [comment]
> I dont think anyone wants this,i certainly dont and it belongs in /opt and out of my /home making clutter. Having to manage multiple paths for no reason is also counter intuitive,nothing beyond 'git clone' & 'git pull' is needed for the work flow.

Valid opinion, but obviously people want a simpler install method. You might grok how to deal with the updates from the repo, but plenty of others find it difficult. 

As for the locations and all that, you can just set it to wherever you want. If you want to keep everything in place just pass those into the CLI call or put it in the `.settings/config.json`.

It shouldn't affect your git clone and pull "workflow" since you can still just point it at the same script and run it, but makes installing it much easier for people who don't understand git (or python virtualenvs). At most you'd just set the folder locations to where they currently are.


---
The directories mentioned make use standards (specifically [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) spec). Just so that they follow common conventions instead of randomly throwing themselves everywhere.

**Comment by HistoricTheater** [comment]
> but makes installing it much easier for people who don't understand git 

it takes like 2 minutes to learn/comprehend how to clone and pull to get updates. It would be easier and more understandable to educate people how to use the core system (git clone & git pull) then come up with ways to make it more complicated then it needs to be.

This smells of white knight projecting on a project that dosent need any changes, for the sake of changes to get recognition.

>XDG

XDG is a layer below the hierarchy
[LFH](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/Linux-Filesystem-Hierarchy.html#opt)
If this program were to be packaged by arch or debian or fedora,it would go in /opt.

**Comment by HistoricTheater** [comment]
So who is teaching them how to install and use pip? Is their distro bleeding edge and using python 3.10.X? Or do they also need to install that separately?(perhaps in a chroot? requiring a ENVAR to be passed each time its executed?) You used an argument and a switch in your example, how are they learning those switches and arguments being a 0day newbie? Its the same level of effort to git clone & git pull as your workflow

Your efforts of "making it easy" cascade backwards at every step.

See project
git clone project
read github page docs
use project
git pull on updates
Done. This project does not support partial updates or using anything that isnt the latest commit,given the nature of what it is doing.

**Comment by stranger-danger-zamu** [comment]
> So who is teaching them how to install and use pip? [...] workflow

Lol if they can't figure out a CLI then they probably can't figure out how to get the auth credentials from their browser making them non-issues.

And you are also forgetting it's more then just git clone & pull, the users also have to install python and all of OF's dependencies which can mean that someone might clobber their operating system python installs by forgetting to activate a virtualenv or missing the `--user` flag in pip. 

Not to mention that this lets the entire codebase and it's dependencies be distributed in a single file which is much easier to update (utilizing zipapp and/or shiv). It'd also update all the dependencies in one go as well, so no more bitching and moaning about that being an issue. It's impossible to partially update a single file if they are just overwriting it.

Unless you have actual criticism beyond it interrupting your workflow I don't think there is more to discuss.

**Comment by MonkeyKingViper** [comment]
For what it's worth, coming from a total pleb that just needed a way to rip OF...what SD is suggesting seems wildly complicated vs how it needs to be.

I come to the page
I download the zip file
I extract it
I move my .Sites folder from one to the the other.
I get in CMD and do the pip install -r requirements.txt and it works
I run start_ofd.py from the folder in CMD
I update my settings and config based on the helpful pictures on the main page
it logs me in
I download tits
I am a happy camper

I have no idea what zipapp or shiv is and I don't care. And I don't care how you're trying to package all this into your own thing for whatever ego stroke you're needing. I don't know what CLI is but I figured out how to get the auth credentials easily. Point = moot.

Everything works here pretty dang well. Why mess with a good thing, unless it's benefiting you? No one else needs this. I don't know shit about any of this but I still got it to work pretty easy. Why are you so desperate for it? I barely consider myself part of the "community"...but that still makes it 1 v 1.00000001. Take the L unless the Chief wants to play
