### ISSUE TITLE
Suddenly nothing downloads with VPN

### ISSUE THREAD

**Issue by meanjoep92** [DIGITALCRIMINALS/UltimaScraper#733]
Been using the app for nearly an entire year. I've even managed to scrape several profiles a few days ago, but the past two days the scraper doesn't download anything. It now goes straight to "Archive complete' when trying to scrape a profile. I haven't changed any settings.

UPDATE: So apparently, it seems to be an issue revolving around the VPN I'm using. I've tried changing locations. Now it'll just download one video and then say 'Archive Complete' (Remember this had cause problems with authentication one time) Not sure if any dev's might've noticed this.

**Comment by TheMissingPort** [comment]
Still having this issue as well

**Comment by meanjoep92** [comment]
UPDATE: So apparently, it seems to be an issue revolving around the VPN I'm using. (Remember this had cause problems with authentication one time) Not sure if any dev's might've noticed this.

**Comment by jp1151419** [comment]
I've noticed multiple IP addresses of my VPN getting blocked recently. I just tried alternative ones until one worked.
