### ISSUE TITLE
Doesn't download videos and previews from Fansly

### ISSUE THREAD

**Issue by Rocket3192** [DIGITALCRIMINALS/UltimaScraper#778]
Hello, I finally made the script work it downloaded some pictures but not a single video, another scrapper succeeded to download 3 videos of the same model, and all images, so I know they are there, is there a setting I'm missing ?

Thank you

**Comment by Rocket3192** [comment]
Ok so while comparing the 2 scrapper output folders I figured the "preview" pictures are not being downloaded, they are the ones missing, for the videos I don't really know, one of them was indeed a preview, but 2 others were not

**Comment by DIGITALCRIMINALS** [comment]
You can update the script

**Comment by Jotund** [comment]
There is one paid video on fansly in messages that refuses to download. Seems when in the process of scraping, it is getting recognized, but download does not trigger. Everything else works fine for me.

**Comment by Rocket3192** [comment]
So I did the update, it doesn't download more stuff than it used to do before the update :)

**Comment by DIGITALCRIMINALS** [comment]
I fixed messages in the latest commit

**Comment by Rocket3192** [comment]
Up, still not downloading everything available :)

**Comment by DIGITALCRIMINALS** [comment]
Does it still not get the paid video in the latest update?
