### ISSUE TITLE
Scraper downloads one file and stops working

### ISSUE THREAD

**Issue by Kenkai87** [DIGITALCRIMINALS/UltimaScraper#900]
I'm having trouble scraping content. the scraper stops when initializing a download and downloads like 1 thing and stops.
maybe my config,json ? I'm not sure.....
Currently, I'm using poetry ver. 1.4.0.....

**Comment by CannotTouch** [comment]
try to login from browser when it stuck, probably you will be under a temporary ip ban like we talk here https://github.com/DIGITALCRIMINALS/OnlyFans/issues/838

**Comment by Kenkai87** [comment]
I'm not banned I have the older version of the scraper and it works fine, I just wanted to test the newer ver in a separate folder.

**Comment by Kenkai87** [comment]
I can also login online no issue.

**Comment by luckybear992** [comment]
how can I go back to the older version of the scrapper?
