### ISSUE TITLE
Wrong subscription scraped

### ISSUE THREAD

**Issue by javaded2121** [DIGITALCRIMINALS/UltimaScraper#906]
When prompted to choose subscription I select the one I want to scrape. What ends up being scraped is an expired subscription that isn't even listed as an option. It also doesn't successfully scrape the wrong subscription - there are incomplete files. Tried changing the subscription I want to scrape and it still scrapes the same expired subscription.

**Comment by soulburn74** [comment]
I think this is an issue with the current build. I know I'm also having this issue since installing the master build, and updating it yesterday, after the older build stopped working because of IP ban issues.

**Comment by FFQuarto** [comment]
I also have this problem, there's no fix yet?

**Comment by forminasage** [comment]
I'm hitting this too and even losing content from previously scraped expired subscriptions. I think it's because accounts you used to subscribe to can still send you messages that can be scraped? Disabling scraping messages seems to stop this behavior.
