### ISSUE TITLE
repeated prompts for media

### ISSUE THREAD

**Issue by soulburn74** [DIGITALCRIMINALS/UltimaScraper#907]
[](url)
![image](https://user-images.githubusercontent.com/61853508/225996404-b13db04f-7e1d-4c20-a6ab-afdd20a093e6.png)
after installing Master code, and running updater, trying to use. it allows me to choose model, then asks for media type, but then keeps asking....... over and over........

**Comment by porncritic** [comment]
same issue for about a week now (OF obviously changed something), everything worked up until then, without updating my commit since 2021 (and even now that still works for models that dont message (and/or maybe dont post that much) got poetry (which I didnt have before, and updated to recent commit) and getting the same thing

**Comment by soulburn74** [comment]
Well at least I know I'm current, and its helpful to know that its not a misconfig on my end if other's are experiencing the same, will wait patiently until a resolution is made (I went down this rabbit hole, due to #429's on the original build that just started happening for everyone.........IP banning etc)....... such is life.......

**Comment by ratu123** [comment]
Just edit this config line in your config file:
"auto_media_choice": "0"

**Comment by soulburn74** [comment]
> 

even doing that, it takes away the repeated prompts, but things still get stuck (they seem to be getting stuck on 'stories', and now, for some reason, even though I choose a certain model, its trying to download stories of a different model, so even with a clean install in new folder (uninstalled Python, reinstalled, installed Poetry, ran updater. things are still a bit off on this newly updated master install. I'm sure things will get situated soon.

**Comment by soulburn74** [comment]
> > 
> 
> even doing that, it takes away the repeated prompts, but things still get stuck (they seem to be getting stuck on 'stories', and now, for some reason, even though I choose a certain model, its trying to download stories of a different model, so even with a clean install in new folder (uninstalled Python, reinstalled, installed Poetry, ran updater. things are still a bit off on this newly updated master install. I'm sure things will get situated soon.

![image](https://user-images.githubusercontent.com/61853508/226079441-9832d3e3-9e7e-448b-8eb6-bcd051dd4d26.png)

AS you can see I choose 2, but its trying to pull data from 51.

**Comment by JOELIN0921** [comment]
I have same problem , I also edit "auto_media_choice": "0" ,but still. 
Thanks for the help! 
![image](https://user-images.githubusercontent.com/69155337/226080395-5b4c33f1-1714-49ca-8d5b-1da5d0e860c0.png)

**Comment by ratu123** [comment]
> I have same problem , I also edit "auto_media_choice": "0" ,but still. Thanks for the help! ![image](https://user-images.githubusercontent.com/69155337/226080395-5b4c33f1-1714-49ca-8d5b-1da5d0e860c0.png)

Im using it right now, and its working, im downloading all the profiles and files. When it says "Download processing" it seems that the script is frozen, but for me it is downloading in the background, if i go to the task manager i can see network usage, and the files are being created on the folder.

**Comment by soulburn74** [comment]
> > I have same problem , I also edit "auto_media_choice": "0" ,but still. Thanks for the help! ![image](https://user-images.githubusercontent.com/69155337/226080395-5b4c33f1-1714-49ca-8d5b-1da5d0e860c0.png)
> 
> Im using it right now, and its working, im downloading all the profiles and files. When it says "Download processing" it seems that the script is frozen, but for me it is downloading in the background, if i go to the task manager i can see network usage, and the files are being created on the folder.
> 
> it seems that the script didnt update on the progress, only when it finishs downloading a stage.

i'm letting it run, just to see what happens. I do see files in the directory that it says is downloading (albeait the wrong model, than I chose).  I see files completed, but also those .parts you are mentioning...........)

**Comment by ratu123** [comment]
> > > I have same problem , I also edit "auto_media_choice": "0" ,but still. Thanks for the help! ![image](https://user-images.githubusercontent.com/69155337/226080395-5b4c33f1-1714-49ca-8d5b-1da5d0e860c0.png)
> > 
> > 
> > Im using it right now, and its working, im downloading all the profiles and files. When it says "Download processing" it seems that the script is frozen, but for me it is downloading in the background, if i go to the task manager i can see network usage, and the files are being created on the folder.
> > it seems that the script didnt update on the progress, only when it finishs downloading a stage.
> 
> i'm letting it run, just to see what happens. I do see files in the directory that it says is downloading (albeait the wrong model, than I chose). I see files completed, but also those .parts you are mentioning...........)

Those .part files will be renamed when it finishs, you can see that is downloading by checking the file count on the folder, it should be increasing.

**Comment by ragnorr** [comment]
how long will it take? for 1 poster , maybe an hour?
And i got some pic like this .
![2316x3088_f2ca1a0949367c1f0d47bac040071cfe](https://user-images.githubusercontent.com/69155337/226092917-f98a1e5b-95bd-45f2-acac-f21252bf4e16.jpg)

**Comment by luckybear992** [comment]
Also having the same problem as everyone else. Max thread of 1 don't change anything. Downloads 1 file. Others show up sometimes as parts file but they are either 0kb or a few kb and broken like the above poster

**Comment by porncritic** [comment]
has this issue been fixed? auto_media_choice": "0 doesnt download from the requested model, it does download a lot of stuff you didnt ask for, and tons of messages from models your not even subscribed to (anymore i think)

**Comment by ragnorr** [comment]
![image](https://user-images.githubusercontent.com/69155337/226224225-06344af4-fb06-4e62-b0c9-d422f7718e1f.png)

I let it run about 24hr or more，and it still no working.

**Comment by debashis66** [comment]
any solution

**Comment by soulburn74** [comment]
Update from a few weeks past og post of mine: there has been a few updates ran a few different times, that have found updates. but situation sill remains similar (it does scrape past many models, but still hangs at one of them). I have a feeling its the specific model, that just has too many posts and the script hangs on it. trying other OF scrapers, that work well for the most part, also getting stuck on same model.........
