### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by skrrrtloder** [DIGITALCRIMINALS/UltimaScraper#908]
Hello,

I keep getting this error message no matter how many times I run the updater. 

Package operations: 23 installs, 0 updates, 0 removals

  • Installing user-agent (0.1.10): Failed

  EnvCommandError

  Command ['/Users/xxx/Library/Caches/pypoetry/virtualenvs/ultima-scraper-Us81GKns-py3.10/bin/pip', 'install', '--no-deps', 'file:///Users/xxx/Library/Caches/pypoetry/artifacts/c0/f1/c7/a620f666a07651ebba6870ff394d9e14e5c8eb2c953490e8c49b3f67c4/user_agent-0.1.10.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/xxx/Library/Caches/pypoetry/artifacts/c0/f1/c7/a620f666a07651ebba6870ff394d9e14e5c8eb2c953490e8c49b3f67c4/user_agent-0.1.10.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
  You should consider upgrading via the '/Users/xxx/Library/Caches/pypoetry/virtualenvs/ultima-scraper-Us81GKns-py3.10/bin/python -m pip install --upgrade pip' command.
  

  at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

**Comment by yvoictra** [comment]
Same issue here.
