### ISSUE TITLE
Scraper doesn't do anything after choosing a subscription

### ISSUE THREAD

**Issue by shixel** [DIGITALCRIMINALS/UltimaScraper#913]
I ran the latest updater hoping to get past the IP lock stuff, but now it doesn't do anything.
I run "poetry run python start_us.py" which then prompts me to choose a site.
I choose OF and it displays my subscriptions and asks me to choose one.
No matter what number I choose, the scraper just sits there and doesn't do anything.

**Comment by elwoodflame** [comment]
I am having the same error. If i select 0 (All) This is what I get.
PS I:\ofrip\onlyfans-master> poetry run python start_us.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Choose Profiles: 0 = All | 1 = default
1
Choose Subscriptions: 0 = All | 1 = ivy_xxxxxxx | 2 = xxxxxxx | 3 = xxxxxxxxxx | 4 = xxxxxxxxx | 5 = xxxxxxxxxxx| 6 = xxxxxxxxxxxxxx | 7 = xxxxxxxxxx | 8 = xxxxxxxxxx | 9 = xxxxxxxxx | 10 = xxxxxxxx | 11 = xxxxxxxxxxx | 12 = xxxxxxxxxxx | 13 = xxxxxxxxxxxxx | 14 = xxxxxxxxxxxxx | 15 = xxxxxxxxxx | 16 = xxxxxxxxxxx | 17 = xxxxxxxxx | 18 = xxxxxxxxxxxxx
0
Processing Scraped Messages
100%|██████████████████████████████████████████████████████████████████████████████| 427/427 [00:00<00:00, 2709.79it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████| 564/564 [00:02<00:00, 256.70it/s]
Download Processing
Name: xxxxxxxxxxxxxxxx | Type: Messages | Downloading: 38 | Total: 38 | Duplicates: 0  | Directory: __user_data__\sites


It will just sit here doing nothing.
thanks for any help.

**Comment by toine512** [comment]
Same as @elwoodflame.

**Comment by rciptv2019** [comment]
same problem

**Comment by kis1yi** [comment]
Same. Tried on 4 computers in different locations, with and without VPN. When download starts, internet traffic goes to zero and CPU usage goes up.

**Comment by ilovescraperz** [comment]
Seems stuck on "download processing" for a model that I didn't chose. High CPU usage but not using much (any?) bandwidth. Shame, I just updated to this branch after have given up on an older one a month or so ago.

Hope it gets fixed soon!

**Comment by Thurlam** [comment]
same issue...looking around at the other recent issues, it seems others are downloading fine even now, so any ideas how to fix this?
