### ISSUE TITLE
Scraper scraping all models after choosing only 1

### ISSUE THREAD

**Issue by RuneDemomn** [DIGITALCRIMINALS/UltimaScraper#915]
My problem is as the title says. I choose 1 model (out of my 37) and the scraper ends up scraping all the models I'm subscribed to, then only downloading the model I chose. This is causing my archiving sessions to take 40+ minutes, or completely freeze up for hours on certain models, something which I suspect is this new IP blocking going around. I used to be able to do 0, choose all, but I'm trying to do 1 model at a time to try and bypass this.

Any help as to what I can change so it doesn't scrape all the models, even after choosing a specific models account?

**Comment by twist3dimages** [comment]
For anyone having the same issue, use this script substituting your path and revision ID. I will output the offending files. For the root_path variable, if you are using Docker, make sure it's the path that the docker container sees
`import os
import sqlite3

revision_id = "offending_revision_id"
root_path = "path_to_of_folder" 

def find_revision_in_database(file_path):
    try:
        conn = sqlite3.connect(file_path)
        cursor = conn.cursor()

        cursor.execute("SELECT version_num FROM alembic_version WHERE version_num=:revision", {"revision": revision_id})
        row = cursor.fetchone()

        if row is not None:
            print(f"Found revision {revision_id} in {file_path}")
            return True

        return False

    except Exception as e:
        print(f"Error checking {file_path}: {e}")
        return False

def search_for_database_files(directory):
    for dirpath, _, filenames in os.walk(directory):
        for filename in filenames:
            if filename == "user_data.db":
                file_path = os.path.abspath(os.path.join(dirpath, filename))

                if find_revision_in_database(file_path):
                    with open("output.txt", "a") as f:
                        f.write(f"{os.path.abspath(dirpath)},{revision_id}\n")
                    return

if __name__ == "__main__":
    with open("output.txt", "w") as f:
        f.write("Path,Revision ID\n")

    search_for_database_files(root_path)
`

**Comment by twist3dimages** [comment]
[coode.txt](https://github.com/DIGITALCRIMINALS/OnlyFans/files/11014158/coode.txt)

**Comment by NumNuts101** [comment]
yeah I am having the same problem
