### ISSUE TITLE
Not downloading all Videos

### ISSUE THREAD

**Issue by god43** [DIGITALCRIMINALS/UltimaScraper#920]
the scraper seems to only download a couple of videos per model, its not catching them all, even on fresh metadata.

**Comment by god43** [comment]
hmm yeah seems like i am missing paid content.

**Comment by rciptv2019** [comment]
For me it's been a couple of weeks that it's impossible for me to finish the process. It gets hung up on the scraping. And it is no longer just because the IP is banned, since when it gets hung up, I can perfectly access the content from the web. 

I also don't see many people reporting bugs and I'm wondering if it's something personal to me or if it's something general. I guess we will have to keep waiting for a new update.

**Comment by god43** [comment]
it looks like it cant download bundles of more than 1 video\pictures.

**Comment by god43** [comment]
looks like its only some models, this is weird.

**Comment by god43** [comment]
its browser based, i used firefox as the agent and my issue cleared up, rather than chrome...interesting.

**Comment by god43** [comment]
lol well this is a lot of comments, its not just browser, but also the ulti scraper, i went back to the 7.6.1 release and it is grabbing all content, the new version does not.

**Comment by god43** [comment]
of course with the old version i run into the rate limiting issue :(

**Comment by excludedBittern8** [comment]
You know you can just edit a comment

**Comment by rciptv2019** [comment]
I have tried to go back to version 7.6.1 as you have commented and it is impossible for me to do the scraping. I directly get "ModuleNotFoundError: No module named 'helpers.main_helper'"

**Comment by rciptv2019** [comment]
I have tried to go back to version 7.6.1 as you have commented and it is impossible for me to do the scraping. I directly get "ModuleNotFoundError: No module named 'helpers.main_helper'"

**Comment by god43** [comment]
> You know you can just edit a comment

lol I know that now. thanks.

**Comment by stubblesticker** [comment]
I'm having this issue too. I'm afraid to try reverting because the installation is such a pain in the ass noawadays.

@god43 have you tried reverting your version?

**Comment by stubblesticker** [comment]
I have the same issue. I even tried reverting to 7.6.1 and downloading into a new folder (basically a completely fresh install), some free videos in posts that are bundled with pictures just don't download.

**Comment by toine512** [comment]
> I also don't see many people reporting bugs and I'm wondering if it's something personal to me or if it's something general. I guess we will have to keep waiting for a new update.
@rciptv2019 you're not alone #900, #913, #921
