### ISSUE TITLE
Only downloading 1 image & lots of PART files

### ISSUE THREAD

**Issue by MolonelCustard** [DIGITALCRIMINALS/UltimaScraper#921]
I'm having an issue where the script seems to run mostly well until a specific user is chosen, in that, I believe it gets 'stuck' downloading. 

Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████| 117/117 [00:00<00:00, 4656.10it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 3431.09it/s]
Processing Scraped Messages
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.03it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Download Processing
Name: [USERNAME]| Type: Posts | Downloading: 317 | Total: 312 | Duplicates: 5  | Directory: __user_data__\sites

The 'Download Processing' never shows a bar and all I'm left with is one file, sometimes two and a lot of PART files, sometimes I also end up with some corrupted or distorted image files.

Even if left for hours, this doesn't change. 

Its also worth noting that I have to manually the username I want to download from in the config file as it always defaults to one I haven't selected. It also tends, if not edited in config, to ask which kind of media I want to download multiple times. 

Perhaps there's something really obvious I'm missing, as I've downloaded even older versions of the code and have exactly the same issue.

**Comment by ficarra1002** [comment]
Also having this issue

**Comment by toine512** [comment]
Same here.
#900 #913

**Comment by machinesean** [comment]
same. hasn't worked for me in weeks.

**Comment by ficarra1002** [comment]
Still experiencing this issue after latest commits, if there's some way to enable detailed logs I'd be more than willing to submit that to help find the issue

**Comment by ficarra1002** [comment]
Still hanging with latest commit, here is the output if it helps determine where it's getting stuck: 

`D:\Onlyfans>poetry run python start_us.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Choose Profiles: 0 = All | 1 = default
1
Choose Subscriptions: 0 = All | 1 = asdf | 2 = asdf | 3 = asdf | 4 = asdf | 5 = asdf | 6 = asdf | 7 = asdf
3
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Processing Scraped Stories
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 3996.86it/s]
Processing metadata.
asdf: Renaming files.
100%|█████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 799.31it/s]
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████| 742/742 [00:00<00:00, 1886.42it/s]
Processing metadata.
asdf: Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████| 742/742 [00:01<00:00, 566.14it/s]
Processing Scraped Messages
100%|██████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 4993.22it/s]
Processing metadata.
asdf: Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 713.68it/s]
Processing Download:
Name: asdf | Type: Stories | Downloading: 30 | Total: 30 | Duplicates: 0 | Directory: __user_data__\sites\OnlyFans\asdf`

**Comment by DIGITALCRIMINALS** [comment]
I finally logged onto windows and experienced the same thing. It was to do with formatting images.

**Comment by DIGITALCRIMINALS** [comment]
You need to run the updater script if you want it to work. No longer hangs for me.
It was due to a missing package I forgot to include.

**Comment by ficarra1002** [comment]
Pretty sure that did it, it's working so far.
