### ISSUE TITLE
models with many posts timeing system out

### ISSUE THREAD

**Issue by god43** [DIGITALCRIMINALS/UltimaScraper#923]
models that have over 10k posts are timing out and stopping the scraper.

Edit:

it looks like 7k posts is the limit and it times out.

**Comment by Bun-Bun** [comment]
This is happening to me as well, the blacklist function isn't working either.

**Comment by soulburn74** [comment]
Same, even on other of scrapers I've found one specific model has over 17k posts in archived, and its causing the script to seemingly hang. I've left it running for hours, and still hasn't progressed past it but I do see periodic movement from memory and network on python, so I'm letting it run over night this time, to see if it finally progresses past....*fingers crossed* If I can get past this specific model, I think I'm good entirely (not on this script but a different one....)

**Comment by Bun-Bun** [comment]
I found a workaround for myself. 

I run the script inside of a linux VM running on a Hyper-V host. I pause the VM when I encounter the rate limiting from onlyfans. Wait for the rate limit to be lifted (usually a few minutes) and then resume the VM and the script continues on like normal.

**Comment by god43** [comment]
> I found a workaround for myself.
> 
> I run the script inside of a linux VM running on a Hyper-V host. I pause the VM when I encounter the rate limiting from onlyfans. Wait for the rate limit to be lifted (usually a few minutes) and then resume the VM and the script continues on like normal.

nice

**Comment by DIGITALCRIMINALS** [comment]
Latest commit resolves rate limiting automatically now, and will resume the script once it's stops.
