### ISSUE TITLE
Avoid the List of subscription

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINALS/UltimaScraper#925]
with the restriction to the quantity of the connection before the temporary ban I was thinking if is possible avoid the scrape of the list of subscrption at the start.
I yet know the names that i wanna submit to scrape, so if is possible avoid it will be nice.

**Comment by TMD20** [comment]
This has been very confusing to me as well. From what I've read some settings like messages in the json will cause scraping of all models. 

If you want a little more control over this check out 
https://github.com/excludedBittern8/ofscraper

**Comment by DIGITALCRIMINALS** [comment]
RTFD
