### ISSUE TITLE
{"cookie":"cookie_value"}

### ISSUE THREAD

**Issue by Xknight79** [DIGITALCRIMINALS/UltimaScraper#926]
which cookie value do we have to enter is it only sess or anything else

**Comment by Jarsky** [comment]
Just copy the entire cookie string (right click it and copy) and paste it in. When you load Ultima Scraper it will remove all unnecessary cookie info. 

![image](https://user-images.githubusercontent.com/839416/228997745-6a0e32e3-bdc1-47b8-9a32-82d5de91b458.png)
