### ISSUE TITLE
Help please, what am I doing wrong?

### ISSUE THREAD

**Issue by chrome2ru** [DIGITALCRIMINALS/UltimaScraper#927]
Help please, what am I doing wrong?
Run script, select OnlyFans, select model 1 = jakeline.0306, select 0 = All
And something went wrong
![Снимок экрана (100)](https://user-images.githubusercontent.com/92716998/229130292-c75f2752-507c-4c65-876c-643757317a18.png)
does not pump

**Comment by deadcode0815** [comment]
for some reason you have to choose media for all the models you have, even when you choose one particular. I'm experiencing the same

**Comment by soulburn74** [comment]
I'm also in this state, even if you modify your settings to auto choose 0 to stop the loop, it still doesn't work quite right.
