### ISSUE TITLE
Can't get poetry to work and directory errors

### ISSUE THREAD

**Issue by MozartWolfgang** [DIGITALCRIMINALS/UltimaScraper#933]
I have now tried for multiple days to get poetry to work, it will install correctly but when i try to run it, it just says poetry isnt a real command which annoys me to all hell... 
i have tried a mix of both version of the scraper, both the 7.6.1 and updating that with everything necessary and i have tried to just download the master and i have tried to mix both and nothing will work. 
When i launch one of the py programs such as the updater, it just closes instantly even after pc restarts, and i have updated python and tried different versions.
Did i install poetry incorrectly ? did i miss something? is there something in the files i need to change? is there a step-by-step guide somewhere i have missed ?

update.py error:
E:\!!Onlyfans_Scraper\OnlyFans-7.6>python updater.py
Traceback (most recent call last):
  File "E:\!!Onlyfans_Scraper\OnlyFans-7.6\updater.py", line 50, in <module>
    subprocess.run(["poetry", "update"])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

start_ofd.py error:
E:\!!Onlyfans_Scraper\OnlyFans-7.6>python start_ofd.py
Traceback (most recent call last):
  File "E:\!!Onlyfans_Scraper\OnlyFans-7.6\start_ofd.py", line 20, in <module>
    main_test.check_config()
TypeError: check_config() missing 1 required positional argument: 'directory'

start_us.py error:
E:\!!Onlyfans_Scraper\OnlyFans-7.6>python start_us.py
Traceback (most recent call last):
  File "E:\!!Onlyfans_Scraper\OnlyFans-7.6\start_us.py", line 22, in <module>
    main_test.check_start_up()
  File "E:\!!Onlyfans_Scraper\OnlyFans-7.6\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'

**Comment by jdkjdji** [comment]
Hello, I use mac, so... i don't know if the solution works in windows. but, i'm install in terminal postgresql, and run again  python updater.py  and works...!

**Comment by soulburn74** [comment]
The most important thing about getting poetry to install properly, is then locating where poetry.exe resides after install, and then setting that in your path statements in system config (system path, not user path).  Once you get to where you can just type 'poetry' inside a cmdline or powershell cmd line and it takes you to poetry cmd line, then you know you are good with poetry install.

**Comment by qwertitties** [comment]
I just ran into these exact problems on windows, subprocess.run needs to have an additional argument passed in to allow it to run a shell. 

Changing line 50 of of updater.py to `subprocess.run(["poetry", "update"], shell=True)` made it work for me. 

Also make sure you have poetry added to your path, as previously stated.

**Comment by MozartWolfgang** [comment]
After a shit ton of python messing shit up and windows version python messing shit up i finally got it "fixed" so now i can finally run python independently and poetry but now it says `Traceback (most recent call last):
  File "C:\Users\USERNAME\Desktop\OnlyFans-7.6.1\updater.py", line 8, in <module>
    import requests.get
ModuleNotFoundError: No module named 'requests'`
and im honestly so OMEGA lost, i have absolutely no idea what to do and also the python scripts just closes instantly now when trying to run them even tho i have py launcher and all that
