### ISSUE TITLE
does this even work at all?

### ISSUE THREAD

**Issue by machinesean** [DIGITALCRIMINALS/UltimaScraper#941]
I'm honestly giving up. it hasn't worked for me in months, and I've tried everything I can think of. all it does is download a single image, a couple .parts, and stops. everything is updated, everything is configured, I'm just... out of ideas. taux1c's scrip is looking a lot better these days.

**Comment by Bearded-Beard** [comment]
Go here and read this, its helped a lot of people. https://github.com/DIGITALCRIMINALS/OnlyFans/issues/902

**Comment by twist3dimages** [comment]
> I'm honestly giving up. it hasn't worked for me in months, and I've tried everything I can think of. all it does is download a single image, a couple .parts, and stops. everything is updated, everything is configured, I'm just... out of ideas. taux1c's scrip is looking a lot better these days.

It used to very well but there have been a few modifications last few updates that broke important functionality

**Comment by betoalanis** [comment]
I made it work and was able to DL about 50GB of content  by reinstalling everything after a problem with my computer and needing to reformat my drive. And by everything I mean EVERYTHING, i started from python.. and step by step installing each thing that the script was telling me was missing, **step by step**, meaning didn't install anything I thought I needed until the script itself installed it or asked for it. (I'm on Mac BTW)

also, i lowered my max thread to 2.

I don't mean for you guys to reformat your drives, but if possible, uninstall all the dependencies and start from scratch.

**Comment by DIGITALCRIMINALS** [comment]
Yes, I use it everyday

![image](https://user-images.githubusercontent.com/89371864/233539875-d9d98938-11cb-4a8d-bf19-337c1e10c454.png)
