### ISSUE TITLE
Incomplete video downloads after a recent update

### ISSUE THREAD

**Issue by e2489** [DIGITALCRIMINALS/UltimaScraper#944]
This issue existed a long time ago, and then it was fixed, and now it's back after a recent update. Videos are only partially downloading before moving on to the next. Then I have to go through, delete those, re-download, repeat until I have the complete files. Very annoying, hopefully we get a fix for this.

**Comment by verdetren** [comment]
I Created an account just to report this.

**Comment by DIGITALCRIMINALS** [comment]
Try latest commit
