### ISSUE TITLE
'NoneType' object has no attribute 'directory'

### ISSUE THREAD

**Issue by Solandus** [DIGITALCRIMINALS/UltimaScraper#950]
After updating to the latest commit I'm now getting into a loop. console output shows this:

...
Processing Scraped Stories
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1998.24it/s]
Processing metadata.
XXXX: Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 185.89it/s]
Processing Scraped Posts
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 480/480 [00:00<00:00, 3579.04it/s]
Processing metadata.
XXXX: Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 480/480 [00:02<00:00, 223.38it/s]
Processing Scraped Messages
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 5997.57it/s]
Processing metadata.
XXXX: Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 477.85it/s]
Download Processing
Name: XXXX | Type: Posts | Downloading: 460 | Total: 1 | Duplicates: -459  | Directory: .sites

'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
'NoneType' object has no attribute 'directory'
and so on. it never ends

**Comment by rknightion** [comment]
Same here. Also looks like it's going to re-download everything:
```Downloading: 460 | Total: 1 | Duplicates: -459 | Directory: .sites```

**Comment by ChillyP** [comment]
Hitting the same issue, traceback below

>'NoneType' object has no attribute 'directory'
Traceback (most recent call last):
  File "C:\GitHub\OnlyFans\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 792, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)

**Comment by tedy02** [comment]
same after but only after it starts downloading video and images in the message category for a model I've never subscribed to or communicated with or even heard of for that matter.

**Comment by DIGITALCRIMINALS** [comment]
Run the updater

**Comment by ChillyP** [comment]
I’m getting the same issue still

**Comment by lEtranger1942** [comment]
Same issue after update

**Comment by fl4shforward** [comment]
Still happening with commit https://github.com/DIGITALCRIMINALS/UltimaScraper/commit/c20489261bc2bd39d96cd473923133c08c0c5681

**Comment by twist3dimages** [comment]
Having the same issue

**Comment by Solandus** [comment]
Still happening with [dfcace3](https://github.com/DIGITALCRIMINALS/UltimaScraper/commit/dfcace3813aac3a0580d651574bc1e6a179641ff)

**Comment by DIGITALCRIMINALS** [comment]
I got the error, and know what's wrong. Will push a fix in a few hours.

**Comment by DIGITALCRIMINALS** [comment]
Can try now, also you should see "downloading" be a more sensible number since you've probably got overwrite files set to false.

**Comment by Nostang3** [comment]
Can confirm `4c687e7 `worked for me. I had to rename a directory the first time but after that it worked fine.

**Comment by Solandus** [comment]
Can also confirm. works for me, without renaming something. Can be closed for me.

**Comment by tedy02** [comment]
fixed. thank you for being on it.

**Comment by spreagit** [comment]
same problem with last version....when script try to overwrite something

**Comment by tedy02** [comment]
make sure you used python updater.py cmd to get any changes
