### ISSUE TITLE
Can't figure out correct format for directory paths

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/UltimaScraper#965]
I keep getting this error because of how the "download_directories" and "metadata_directories" fields are formatted in config ("Y:/OnlyFans"):

> C:\Users\username\Desktop\UltimaScraper-masterpoetry run python start_us.py
> Traceback (most recent call last):
> File "C:\Users\username\Desktop\UltimaScraper-master\start_us.py", line 62, in
> asyncio.run(main())
> File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
> return runner.run(main)
> ^^^^^^^^^^^^^^^^
> File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
> return self._loop.run_until_complete(task)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
> return future.result()
> ^^^^^^^^^^^^^^^
> File "C:\Users\username\Desktop\UltimaScraper-master\start_us.py", line 44, in main
> _api = await USR.start(
> ^^^^^^^^^^^^^^^^
> File "C:\Users\username\Desktop\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 49, in start
> datascraper.filesystem_manager.activate_directory_manager(api_)
> File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-LYaChEfD-py3.11\Lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 64, in activate_directory_manager
> root_metadata_directory = main_helper.check_space(
> ^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-LYaChEfD-py3.11\Lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 136, in check_space
> obj_Disk = disk_usage(str(download_path.parent))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-LYaChEfD-py3.11\Lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 50, in disk_usage
> raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), path)
> FileNotFoundError: [Errno 2] No such file or directory: 'Y:\\'

What is the correct way of formatting "Y:/OnlyFans" if I'm on Windows? I've tried all sorts of different forward/back slash combinations, and I keep getting the same error.

**Comment by DIGITALCRIMINALS** [comment]
You're only supposed to use forward slashes.

**Comment by avekifes** [comment]
> You're only supposed to use forward slashes or double backslashes

Yeah, this seems like an obvious fix, but so far, I've tried:

Y:\\OnlyFans (script resets my directories "__user_data__/sites")
Y:/OnlyFans (FileNotFoundError: [Errno 2] No such file or directory: 'Y:\\')

I've run out of ideas. Could part of the problem be that my Y drive is a network drive?

**Comment by puc9** [comment]
Sounds a bit silly, I know, but can you do a dir Y:\ from the same place you are starting the scraper to check that the drive letter is visible?
An alternative would be to move the scraper to Y: in some subfolder and only use relative paths, in your case /Onlyfans

**Comment by shixel** [comment]
I'm getting the same errors with the new build.

**Comment by avekifes** [comment]
I eventually got it working, although I'm not sure what I did. The script eventually initialized and pulled up config.txt, and when I checked it, it kept my preferred directory (Y:/OnlyFans).
