### ISSUE TITLE
Installing psycopg2 (2.9.6): Failed

### ISSUE THREAD

**Issue by andzzzzz** [DIGITALCRIMINALS/UltimaScraper#976]
update.py fails installing psycopg2:

`Package operations: 4 installs, 2 updates, 0 removals

  • Updating sqlalchemy (2.0.10 -> 2.0.11)
  • Updating platformdirs (3.3.0 -> 3.5.0)
  • Installing psycopg2 (2.9.6): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /tmp/tmpayvs9aww/.venv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!
  
          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.
  
          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
  
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
  
  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing psycopg2.egg-info/PKG-INFO
  writing dependency_links to psycopg2.egg-info/dependency_links.txt
  writing top-level names to psycopg2.egg-info/top_level.txt
  
  Error: pg_config executable not found.
  
  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:
  
      python setup.py build_ext --pg-config /path/to/pg_config build ...
  
  or with the pg_config option in 'setup.cfg'.
  
  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
  
  

  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.6) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psycopg2 (==2.9.6)"'.

Script has been updated, exiting in 5 seconds
`

**Comment by AndrePuls** [comment]
> 
> Error: pg_config executable not found.
> 
> pg_config is required to build psycopg2 from source. Please add the directory containing pg_config to the $PATH or specify the full executable path with the option:

That's your problem. Try
`apt update && apt install libpq-dev`
(for Debian/Ubuntu and others)

You may have to Logout and back In to make sure, the $PATH gets updated and reloaded.

**Comment by betoalanis** [comment]
I had this error and this is what I did to solve it, all in terminal:

1. Install Brew
2. Install postgresql via brew
3. Run updater again and psycopg2 will be installed

After this you can actually uninstall brew, which will uninstall postgresql automatically  if you think you dont need them for anything else, the updater just needs postgresql to install psycopg2

**Comment by andzzzzz** [comment]
> > Error: pg_config executable not found.
> > pg_config is required to build psycopg2 from source. Please add the directory containing pg_config to the $PATH or specify the full executable path with the option:
> 
> That's your problem. Try `apt update && apt install libpq-dev` (for Debian/Ubuntu and others)
> 
> You may have to Logout and back In to make sure, the $PATH gets updated and reloaded.

That solved the problem.
Thank you very much!
